version: '3.4'

services:
  ci-build:
    image: mcr.microsoft.com/dotnet/aspnet:5.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./ReportService.sln && dotnet publish ./ReportService.sln -c Release -o ./obj/Docker/publish"
